FROM node:14 as builder

WORKDIR /app/intero-server

COPY ./ ./
RUN npm install
RUN npx nx build intero-api


FROM node:14 as runner

WORKDIR /app/intero-api
COPY ./package*.json ./
COPY --from=builder /app/intero-server/dist/apps/intero-api-delivery/ .

RUN npm install --production

EXPOSE 3333

CMD [ "node", "main.js" ]
