import { Body, Controller, Get, HttpCode, HttpStatus } from '@nestjs/common';
import { ApiOkResponse } from '@nestjs/swagger';
import { W2fpDto } from './w2fp.dto';

import * as tf from '@tensorflow/tfjs-node';

@Controller('/w2fp')
export class W2fpController {
  @Get()
  @HttpCode(HttpStatus.OK)
  @ApiOkResponse({
    description:
      'An image of a floor plan design, generated by a neural network.',
  })
  async get(@Body() body: W2fpDto) {
    // Load the neural network
    // Run prediction from neural network
    const model = await tf.loadLayersModel(
      `https://raw.githubusercontent.com/braind3d/intero-ai/main/models/tfjs/model.json`,
      {
        weightPathPrefix: `https://raw.githubusercontent.com/main/intero-ai/main/models/tfjs/`,
      }
    );

    const queryTensor = tf.tensor(body.query);
    const prediction = model.predict(queryTensor);

    return prediction;
  }
}
